### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by shreydhiman99** [netbiosX/AMSI-Provider#1]
![Captureerror](https://user-images.githubusercontent.com/46566320/118658836-647c8d00-b80a-11eb-9d18-ade9f3e98162.PNG)

**Comment by netbiosX** [comment]
Make sure you execute regsvr32 from an elevated command prompt. Run cmd.exe as an administrator and it should work.

**Comment by shreydhiman99** [comment]
running from elevated priv.
![Capture23](https://user-images.githubusercontent.com/46566320/118660756-1bc5d380-b80c-11eb-9069-a6f32f9e0d38.PNG)

**Comment by netbiosX** [comment]
You might be missing some dependencies. Try to download on your VM Microsoft Visual C++ Redistributable. You can find it below and let me know.
https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by shreydhiman99** [comment]
Thankyou Sir, now its working.
![Capture44](https://user-images.githubusercontent.com/46566320/118671242-ed002b00-b814-11eb-881b-a7da17433b22.PNG)
